version: '3.4'

services:
  vogcodechallenge.api:
    image: ${DOCKER_REGISTRY-}vogcodechallengeapi
    ports:
     - 80
     - 443
    build:
      context: .
      dockerfile: VogCodeChallenge.API/Dockerfile
